# Generated by Django 5.2.14 on 2026-05-19 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=20)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('tin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(max_length=80)),
                ('sector', models.CharField(max_length=80)),
                ('location_description', models.CharField(blank=True, max_length=180)),
                ('stock_focus', models.CharField(blank=True, max_length=120)),
                ('monthly_revenue_band', models.CharField(blank=True, max_length=80)),
                ('employee_count', models.PositiveSmallIntegerField(default=1)),
                ('is_demo_account', models.BooleanField(default=False)),
                ('tax_lookup_status', models.CharField(choices=[('not_provided', 'TIN not provided'), ('ready_for_lookup', 'Ready for tax lookup'), ('demo_bypass', 'Demo account bypass')], default='not_provided', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('government', 'Government officer'), ('lender', 'Lender'), ('field_agent', 'Field agent')], max_length=20)),
                ('requires_tin', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
