# Generated by Django 5.2.14 on 2026-05-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistrationChainState',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('latest_index', models.PositiveBigIntegerField(default=0)),
                ('latest_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business registration ledger state',
                'verbose_name_plural': 'business registration ledger state',
            },
        ),
        migrations.CreateModel(
            name='BusinessRegistrationLedgerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_index', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=10)),
                ('previous_hash', models.CharField(editable=False, max_length=64)),
                ('block_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_blocks', to='registry.businessregistration')),
            ],
            options={
                'ordering': ['chain_index'],
            },
        ),
    ]
