# Generated by Django 5.2.14 on 2026-05-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_businessregistrationchainstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSecurityChainState',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('latest_index', models.PositiveBigIntegerField(default=0)),
                ('latest_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('latest_signature', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'app security ledger state',
                'verbose_name_plural': 'app security ledger state',
            },
        ),
        migrations.CreateModel(
            name='AppSecurityLedgerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_index', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('domain', models.CharField(choices=[('auth', 'Authentication'), ('business_registration', 'Business registration'), ('demo_access_profile', 'Demo access profile'), ('user_account', 'User account')], max_length=40)),
                ('event_type', models.CharField(max_length=40)),
                ('entity_key', models.CharField(max_length=160)),
                ('actor_identifier', models.CharField(blank=True, max_length=120)),
                ('previous_hash', models.CharField(editable=False, max_length=64)),
                ('block_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('signature', models.CharField(editable=False, max_length=64)),
                ('payload', models.JSONField()),
                ('recorded_at', models.DateTimeField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['chain_index'],
            },
        ),
    ]
