# Generated by Django 5.2.14 on 2026-05-21 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_appsecuritychainstate_appsecurityledgerblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='account_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demoaccessprofile',
            name='role',
            field=models.CharField(choices=[('government', 'Government officer'), ('lender', 'Lender'), ('field_agent', 'Field agent'), ('business_owner', 'Business owner')], max_length=20),
        ),
    ]
