# Generated by Django 5.2.14 on 2026-05-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_businessregistration_account_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='average_monthly_mobile_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='average_monthly_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='credit_registration_reference',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='credit_registration_status',
            field=models.CharField(choices=[('not_started', 'Not ready for credit registration'), ('eligible', 'Eligible for credit registration'), ('submitted', 'Credit registration submitted'), ('verified', 'Credit registration verified')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='credit_registration_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='inventory_value_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='nin_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='nin_verification_notes',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='nin_verification_source',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='nin_verification_status',
            field=models.CharField(choices=[('not_submitted', 'NIN not submitted'), ('pending', 'Pending NIRA or NITA verification'), ('verified', 'Verified through NIRA or NITA'), ('manual_review', 'Manual review required')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='receipt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='receipt_value_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
