# Generated by Django 5.2.14 on 2026-05-22 06:52

import registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_businessregistration_average_monthly_mobile_money_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfiguration',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('registration_form', models.JSONField(default=registry.models.default_platform_registration_form)),
                ('score_breakdown', models.JSONField(default=list)),
                ('loan_programs', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'platform configuration',
                'verbose_name_plural': 'platform configuration',
            },
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='workspace_payload',
            field=models.JSONField(blank=True, default=registry.models.default_owner_workspace_payload),
        ),
    ]
